// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addwritersskills_skillpercent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addwritersskills_skillpercent));
        
        string IMigrationMetadata.Id
        {
            get { return "202106170524221_add-writersskills_skillpercent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
